USE [master]
GO

/****** Object:  Database [CheerfulGiver]    Script Date: 2/18/2026 12:15:26 AM ******/
CREATE DATABASE [CheerfulGiver]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CheerfulGiver', FILENAME = N'D:\CodeProjects\CheerfulGiver\Database\CheerfulGiver.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CheerfulGiver_log', FILENAME = N'D:\CodeProjects\CheerfulGiver\Database\CheerfulGiver_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CheerfulGiver].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CheerfulGiver] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CheerfulGiver] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CheerfulGiver] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CheerfulGiver] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CheerfulGiver] SET ARITHABORT OFF 
GO

ALTER DATABASE [CheerfulGiver] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CheerfulGiver] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CheerfulGiver] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CheerfulGiver] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CheerfulGiver] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CheerfulGiver] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CheerfulGiver] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CheerfulGiver] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CheerfulGiver] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CheerfulGiver] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CheerfulGiver] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CheerfulGiver] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CheerfulGiver] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CheerfulGiver] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CheerfulGiver] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CheerfulGiver] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CheerfulGiver] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CheerfulGiver] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [CheerfulGiver] SET  MULTI_USER 
GO

ALTER DATABASE [CheerfulGiver] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CheerfulGiver] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CheerfulGiver] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CheerfulGiver] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [CheerfulGiver] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CheerfulGiver] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [CheerfulGiver] SET QUERY_STORE = ON
GO

ALTER DATABASE [CheerfulGiver] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [CheerfulGiver] SET  READ_WRITE 
GO

